@startuml

skinparam monochrome true
hide circle
skinparam classAttributeIconSize 0

' =====================
' CARD HIERARCHY
' =====================
interface SpecialEffect <<interface>> {
  +apply(owner: Player, opponent: Player)
}

abstract class Card <<abstract>> {
  -name: String
  -description: String
  +Card(name: String, description: String): Card
  +play(owner: Player, opponent: Player): void
}

class Unit {
  -basePoint: int
  -rowType: RowType
  -currentPoint: int
  +Unit(name: String, description: String, basePoint: int, rowType: RowType): Unit
  +getPoints(): int
  +play(owner: Player, opponent: Player): void
}

abstract class Special <<abstract>> {
  +play(owner: Player, opponent: Player): void
}

abstract class Weather <<abstract>> {
  -affectedRow: RowType
  +play(owner: Player, opponent: Player): void
}

abstract class Modifier <<abstract>> {
  -description: String
  +Modifier(description: String): Modifier
  +play(owner: Player, opponent: Player): void
}


' =====================
' RELATIONSHIPS
' =====================

Card <|-- Unit
Card <|-- Special
Special <|-- Weather

Unit --> "*" Modifier
Modifier ..|> SpecialEffect
Special ..|> SpecialEffect

@enduml
