@startuml

skinparam monochrome true
hide circle
skinparam classAttributeIconSize 0

' =====================
' GAME
' =====================
class Game {
  +start()
  +playerPlayCard(card: Card)
  +playerPassRound()
}

class Round {
  -roundNumber: int
  -player1Points: int
  -player2Points: int
  -currentPlayer: Player
  -opponentPlayer: Player
  +Round(player1: Player, player2: Player, titular: Player, roundNumber: int, board: Board): Round
  +nextTurn(): Player
  +currentPlayer(): Player
  +opponentPlayer(): Player
  +playerPassTurn()
  +whoWon(): Player
}

class Player {
  -name: String
  -health: int
  -hand: Hand
  -discardPile: DiscardPile
  -deck: Deck
  -side: Side
  +Player(name: String, health: int): Player
  +getHand(): List<Card>
  +putCardsInDiscardPile(cards: List<Card>): void
  +retrieveNCardsFromDeck(n: int): List<Card>
  +playCard(card: Card, row: RowType): void
  +calculatePoints(): int
  +clearCardsFromSide(): int
}

class DeckBuilder {
  -cards: List<Card>
  -selectedCards: List<Card>
  +getSelection(): List<Card>
  +getCards(): List<Card>
  +selectCard(card: Card)
  +unselectCard(card: Card)
  +buildDeck(): Deck
}

' =====================
' RELATIONSHIPS
' =====================

Game *-- "1..*" Round
Game *-- "2" Player
Game *-- DeckBuilder

@enduml
