@startuml

skinparam monochrome true
hide circle
skinparam classAttributeIconSize 0

' =====================
' GAME
' =====================
class Player {
  -name: String
  -health: int
  +Player(name: String, health: int): Player
  +getDeck(): Deck
  +getHand(): Hand
  +getDiscardPile(): DiscardPile
  +calculatePoints(): int
}

abstract class CardCollection <<abstract>> {
  -cards: List<Card>
  +CardCollection(cards: List<Card>): CardCollection
  +getCards(): List<Card>
  +addCard(card: Card)
  +addCards(List<Card>)
  +retrieveCard(card: Card): Card
  +getCardCount(): int
}

class Hand {
  +getNCardsFromDeck(deck: Deck, n: int)
  +isEmpty(): boolean
}

class DiscardPile {
  +DiscardPile(): DiscardPile
  +getLastCard(): Card
  +addCard(card: Card)
}

class Deck {
  +Deck(cards: List<Card>): Deck
  +getCardCount(): int
  +getUnitsCount(): long
  +getSpecialsCount(): long
}

abstract class Row <<abstract>> {
  -cards: List<Card>
  +placeCard(card: Card)
  +addCard(card: Card)
  +calculatePoints(): int
  +discardCards(discardPile: DiscardPile)
  +addWeather(weather: Weather)
  +canBePlacedIn(unit: Unit): boolean
  +getCards(): List<Card>
}

class Ranged {
  +canBePlacedIn(unit: Unit): boolean
}

class CloseCombat {
  +canBePlacedIn(unit: Unit): boolean
}

class Siege {
  +canBePlacedIn(unit: Unit): boolean
}

class WeatherZone {
  -closeCombatRows: List<Row>
  -rangedRows: List<Row>
  -siegeRows: List<Row>
  +WeatherZone(closeCombatRows: List<Row>, rangedRows: List<Row>, siegeRows: List<Row>): WeatherZone
  +addWeather(weather: Weather)
  +addCloseCombatWeather(weather: Weather)
  +addRangedWeather(weather: Weather)
  +addSiegeWeather(weather: Weather)
}

abstract class Card <<abstract>> {
  -name: String
  -description: String
  +Card(name: String, description: String): Card
  +getName(): String
  +getDescription(): String
  +play(row: Row): void
  +canBePlaced(row: Row): boolean
}

class Unit {
  -basePoints: int
  -currentPoints: int
  -modifiers: List<Modifier>
  -canBeInCloseCombat: boolean
  -canBeInRanged: boolean
  -canBeInSiege: boolean
  +Unit(name: String, description: String, points: int, closeCombat: boolean, ranged: boolean, siege: boolean, modifiers: List<Modifier>): Unit
  +calculatePoints(): int
  +play(row: Row): void
  +resetPoints(): void
  +setPoints(points: int): void
  +haveModifier(modifier: Modifier): boolean
  +canBeInCloseCombat(): boolean
  +canBeInRanged(): boolean
  +canBeInSiege(): boolean
}

abstract class Special <<abstract>> {
  +play(row: Row): void
  +canBePlaced(row: Row): boolean
}

class TightBond {
  +apply(row: Row): void
}

interface Modifier <<interface>> {
  +apply(row: Row): void
}

abstract class Weather <<abstract>> {
  +Weather(name: String, description: String): Weather
  +play(row: Row): void
  +apply(card: Card, row: Row): void
}

class TorrentialRain {
  +TorrentialRain(name: String, description: String): TorrentialRain
}

class ImpenetrableFog {
  +ImpenetrableFog(name: String, description: String): ImpenetrableFog
}

class BitingFrost {
  +BitingFrost(name: String, description: String): BitingFrost
}

class Decoy {
  +Decoy(name: String, description: String): Decoy
}

class TacticalAdvantage {
  +TacticalAdvantage(name: String, description: String): TacticalAdvantage
}

class Scorch {
  +Scorch(name: String, description: String): Scorch
}

interface DeckValidator <<interface>> {
  +validate(): boolean
}

class Validate6SpecialCards {
  -MIN_SPECIALS: int
  -cards: List<Card>
  +Validate6SpecialCards(cards: List<Card>): Validate6SpecialCards
  +validate(): boolean
}

class Validate15UnitsCards {
  -MIN_UNITS: int
  -cards: List<Card>
  +Validate15UnitsCards(cards: List<Card>): Validate15UnitsCards
  +validate(): boolean
}

' =====================
' RELATIONSHIPS
' =====================
Player --> "3" CardCollection
Player --> "3" Row
Player --> "1" WeatherZone

WeatherZone --> "3" Row

CardCollection --> Card
CardCollection <|-- Hand
CardCollection <|-- DiscardPile
CardCollection <|-- Deck

Ranged --|> Row
CloseCombat --|> Row
Siege --|> Row

Row --> Card

Card <|-- Unit
Card <|-- Special
Modifier "*"<- Unit
Modifier <|.. TightBond
Special <|-- Weather
Weather <|-- TorrentialRain
Weather <|-- ImpenetrableFog
Weather <|-- BitingFrost
Special <|-- Decoy
Special <|-- TacticalAdvantage
Special <|-- Scorch

Deck --> "*" DeckValidator
DeckValidator <|.. Validate6SpecialCards
DeckValidator <|.. Validate15UnitsCards

@enduml