@startuml

skinparam monochrome true
hide circle
skinparam classAttributeIconSize 0

left to right direction


interface Section <<interface>> {
  +placeCard(card: Card, round: Round): 
}

abstract class SectionType
class CloseCombatType
class RangedType
class SiegeType
class SpecialType

abstract class Row <<abstract>> {
  #cards: List<Card>
  #lastCard: Unit
  #currentWeather: Weather
  #sectionType: SectionType
  #discardPile : DiscardPile
  #playerColor: PlayerColor
  +Row(sectionType: SectionType, discardPile: DiscardPile): Row
  +placeCard(card: Card, round: Round): 
  +placeCard(card: Card): 
  +addCard(card: Card): 
  +applyWeather(weather: Weather): 
  +applyScorch(scorch: Scorch): 
  +findStrongestCardWithoutHeroModifier(scorch: Scorch): 
  +findAllCardsWithoutHeroModifierWithSamePoints(scorch: Scorch): List<Card>
  +discardCards(card: Card): 
  +containsCard(card: Card): boolean
  +containsCards(cards: List<Card>): boolean
  +calculatePoints(): int
  +discardCards() : 
  +getLastCard(): Unit
  +serColor(playerColor: PlayerColor): 
  +haveSameSectionType(card: Card): boolean
  +getCardCount(): int
  +getCards(): List<Card>
}

class Ranged {
  +Ranged(discardPile : DiscardPile)
}

class CloseCombat {
  +CloseCombat(discardPile : DiscardPile)
}

class Siege {
  +Siege(discardPile : DiscardPile)
}

class SpecialZone {
  -closeCombatRows: List<Row>
  -rangedRows: List<Row>
  -siegeRows: List<Row>
  -weatherCards: List<Card>
  -aDiscardPile: DiscardPile
  -otherDiscardPile: DiscardPile
  -sectionType: SpecialType
  +SpecialZone(closeCombat1: CloseCombat, ranged1: Ranged, siege1: Siege, 
  closeCombat2: CloseCombat, ranged2: Ranged, siege2: Siege, discardPile1: DiscardPile, discardPile2: DiscardPile) 
  +placeCard(card: Card, round: Round): 
  +addCard(card: Card): 
  +clearZone(): 
  +applyCloseCombatWeather(weather: Weather): 
  +applyRangedWeather(weather: Weather): 
  +applySiegeWeather(weather: Weather): 
  +applyScorchInCloseCombat(scorch : Scorch): 
  +applyScorchInRanged(scorch : Scorch): 
  +applyScorchInSiege(scorch : Scorch): 
  +applyScorchInAllRows(scorch : Scorch) : 
}



SpecialZone --> "6" Row

Row <|-- Ranged
Row <|-- CloseCombat
Row <|-- Siege


Row ..|> Section
SpecialZone ..|> Section

SectionType <|-- SpecialType
SectionType <|-- CloseCombatType
SectionType <|-- RangedType
SectionType <|-- SiegeType

SpecialZone --> "1" SectionType
Row --> "1" SectionType

Ranged --> "1" RangedType
CloseCombat --> "1" CloseCombatType
Siege --> "1" SiegeType



@enduml