@startuml

skinparam monochrome true
hide circle
skinparam classAttributeIconSize 0



interface Section <<interface>> {
  +placeCard(card: Card, round: Round): 
}


abstract class Row <<abstract>> {
  #cards: List<Card>
  #lastCard: Unit
  #currentWeather: Weather
  #sectionType: SectionType
  #discardPile : DiscardPile
  #playerColor: PlayerColor
  +Row(sectionType: SectionType, discardPile: DiscardPile): Row
  +placeCard(card: Card, round: Round): 
  +placeCard(card: Card): 
  +addCard(card: Card): 
  +applyWeather(weather: Weather): 
  +applyScorch(scorch: Scorch): 
  +findStrongestCardWithoutHeroModifier(scorch: Scorch): 
  +findAllCardsWithoutHeroModifierWithSamePoints(scorch: Scorch): List<Card>
  +discardCards(card: Card): 
  +containsCard(card: Card): boolean
  +containsCards(cards: List<Card>): boolean
  +calculatePoints(): int
  +discardCards() : 
  +getLastCard(): Unit
  +serColor(playerColor: PlayerColor): 
  +haveSameSectionType(card: Card): boolean
  +getCardCount(): int
  +getCards(): List<Card>
}


class SpecialZone {
  -closeCombatRows: List<Row>
  -rangedRows: List<Row>
  -siegeRows: List<Row>
  -weatherCards: List<Card>
  -aDiscardPile: DiscardPile
  -otherDiscardPile: DiscardPile
  -sectionType: SpecialType
  +SpecialZone(closeCombat1: CloseCombat, ranged1: Ranged, siege1: Siege, 
  closeCombat2: CloseCombat, ranged2: Ranged, siege2: Siege, discardPile1: DiscardPile, discardPile2: DiscardPile) 
  +placeCard(card: Card, round: Round): 
  +addCard(card: Card): 
  +clearZone(): 
  +applyCloseCombatWeather(weather: Weather): 
  +applyRangedWeather(weather: Weather): 
  +applySiegeWeather(weather: Weather): 
  +applyScorchInCloseCombat(scorch : Scorch): 
  +applyScorchInRanged(scorch : Scorch): 
  +applyScorchInSiege(scorch : Scorch): 
  +applyScorchInAllRows(scorch : Scorch) : 
}



SpecialZone -right-> "6" Row




Row ..|> Section
SpecialZone .up.|> Section



@enduml