ignore:
  - "src/main/java/edu/fiuba/algo3/controlador"
  - "src/main/java/edu/fiuba/algo3/vista"
  - "src/main/java/edu/fiuba/algo3/App.java"
  - "src/main/java/edu/fiuba/algo3/Main.java"
  - "src/main/java/edu/fiuba/algo3/SystemInfo.java"
coverage:
  status:
    project:
      default:
        enabled: false  # Desactivamos la regla global por defecto
    patch:
      default:
        enabled: true
        target: 80%     # Cobertura mínima requerida
        threshold: 0%   # No se permite bajar nada
        only_pulls: true
