@startuml

hide footbox
title Aplicación del clima ClearWeather a todas las filas

actor TestCase

participant "specialZone:SpecialZone" as specialZone
participant "clearWeather:ClearWeather" as weather
participant "row:Row" as row
participant "unit:Unit" as unit

TestCase -> specialZone: placeCard(weather)
    activate specialZone
    specialZone -> weather: verifySectionType(sectionType)
        activate weather
        deactivate weather
    specialZone -> weather: play(specialZone)
        activate weather
        weather -> specialZone: applyCloseCombatWeather(weather)
        weather -> specialZone: applyRangedWeather(weather)
        weather -> specialZone: applySiegeWeather(weather)
        loop For each row type (closeCombat, ranged, siege)
            specialZone -> row: applyWeather(weather)
                activate row
                loop For each unit in row
                    row -> weather: apply(unit, row)
                        weather -> unit: resetPoints()
                end
                deactivate row
        end
        deactivate weather
    deactivate specialZone

@enduml
