@startuml

hide footbox
title Aplicación del clima BitingFrost a las filas de combate cercano

actor TestCase

participant "specialZone:SpecialZone" as SpecialZone
participant "bitingFrost:BitingFrost" as Weather
participant "closeCombatRow:CloseCombat" as Row
participant "unit:Unit" as Unit

TestCase -> SpecialZone: placeCard(bitingFrost)
activate SpecialZone

SpecialZone -> Weather: canBePlaced(this)
activate Weather
Weather --> SpecialZone: true
deactivate Weather

SpecialZone -> Weather: play(this)
activate Weather

Weather -> SpecialZone: addCard(this)

SpecialZone -> Weather: addToSpecialZone(this)
Weather -> SpecialZone: addCloseCombatWeather(this)

loop for each closeCombat row
    SpecialZone -> Row: addWeather(this)
    activate Row
    
    loop for each unit in row
        Row -> Unit: apply(this, row)
        activate Unit
        Unit -> Unit: setPoints(1)
        deactivate Unit
    end
    
    deactivate Row
end

deactivate Weather
deactivate SpecialZone

@enduml 