@startuml

hide footbox
title Jugador coloca una Unidad en un Row

actor Jugador

participant "Row (CloseCombat)" as row
participant "Card (Unit)" as unit

Jugador -> row : placeCard(unit)
row -> unit : verify(sectionType)

row -> unit : play(row)
unit -> row : addCard(unit)
@enduml
